-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.channels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  channel_id character varying NOT NULL UNIQUE,
  user_id text NOT NULL,
  project_id uuid,
  channel_name text NOT NULL,
  language_code character varying CHECK (language_code IS NULL OR language_code::text ~* '^[a-z]{2}$'::text),
  language_name text,
  is_master boolean DEFAULT false,
  master_channel_id character varying,
  description text,
  thumbnail_url text,
  subscriber_count bigint DEFAULT 0,
  video_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_paused boolean DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT channels_pkey PRIMARY KEY (id),
  CONSTRAINT fk_channels_project FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT fk_channels_master FOREIGN KEY (master_channel_id) REFERENCES public.channels(channel_id)
);
CREATE TABLE public.contact_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  message text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dubbed_audio (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  translation_id uuid,
  job_id uuid NOT NULL,
  language_code character varying NOT NULL CHECK (language_code::text ~* '^[a-z]{2}$'::text),
  user_id text NOT NULL,
  audio_url text NOT NULL,
  duration integer,
  file_size integer,
  format character varying DEFAULT 'mp3'::character varying,
  voice_id character varying,
  voice_name character varying,
  voice_settings jsonb DEFAULT '{}'::jsonb,
  segments jsonb DEFAULT '[]'::jsonb,
  provider character varying DEFAULT 'elevenlabs'::character varying,
  status character varying DEFAULT 'completed'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dubbed_audio_pkey PRIMARY KEY (id),
  CONSTRAINT dubbed_audio_translation_id_fkey FOREIGN KEY (translation_id) REFERENCES public.translations(id),
  CONSTRAINT dubbed_audio_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id)
);
CREATE TABLE public.lip_sync_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  dubbed_audio_id uuid,
  language_code character varying NOT NULL CHECK (language_code::text ~* '^[a-z]{2}$'::text),
  user_id text NOT NULL,
  synclabs_job_id character varying UNIQUE,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  input_video_url text NOT NULL,
  input_audio_url text NOT NULL,
  output_video_url text,
  quality_score numeric,
  processing_time_seconds integer,
  cost numeric,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT lip_sync_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT lip_sync_jobs_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id),
  CONSTRAINT lip_sync_jobs_dubbed_audio_id_fkey FOREIGN KEY (dubbed_audio_id) REFERENCES public.dubbed_audio(id)
);
CREATE TABLE public.localized_videos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  source_video_id character varying,
  user_id text NOT NULL,
  project_id uuid,
  channel_id character varying,
  language_code character varying NOT NULL CHECK (language_code::text ~* '^[a-z]{2}$'::text),
  title text,
  description text,
  video_url text,
  thumbnail_url text,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['not-started'::character varying::text, 'queued'::character varying::text, 'processing'::character varying::text, 'waiting_approval'::character varying::text, 'draft'::character varying::text, 'live'::character varying::text, 'published'::character varying::text, 'failed'::character varying::text, 'cancelled'::character varying::text])),
  duration integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  localized_video_id character varying,
  deleted_at timestamp with time zone,
  transcript_id uuid,
  translation_id uuid,
  dubbed_audio_id uuid,
  lip_sync_job_id uuid,
  dubbed_audio_url text,
  storage_url text,
  CONSTRAINT localized_videos_pkey PRIMARY KEY (id),
  CONSTRAINT localized_videos_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id),
  CONSTRAINT fk_localized_project FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT fk_localized_source_video FOREIGN KEY (source_video_id) REFERENCES public.videos(video_id),
  CONSTRAINT localized_videos_transcript_id_fkey FOREIGN KEY (transcript_id) REFERENCES public.transcripts(id),
  CONSTRAINT localized_videos_translation_id_fkey FOREIGN KEY (translation_id) REFERENCES public.translations(id),
  CONSTRAINT localized_videos_dubbed_audio_id_fkey FOREIGN KEY (dubbed_audio_id) REFERENCES public.dubbed_audio(id),
  CONSTRAINT localized_videos_lip_sync_job_id_fkey FOREIGN KEY (lip_sync_job_id) REFERENCES public.lip_sync_jobs(id)
);
CREATE TABLE public.processing_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid DEFAULT gen_random_uuid() UNIQUE,
  user_id text NOT NULL,
  project_id uuid,
  source_video_id character varying NOT NULL,
  source_channel_id character varying,
  target_languages ARRAY NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'queued'::character varying::text, 'downloading'::character varying::text, 'transcribing'::character varying::text, 'translating'::character varying::text, 'voice_cloning'::character varying::text, 'dubbing'::character varying::text, 'lip_sync'::character varying::text, 'syncing'::character varying::text, 'assembling'::character varying::text, 'processing'::character varying::text, 'waiting_approval'::character varying::text, 'uploading'::character varying::text, 'ready'::character varying::text, 'completed'::character varying::text, 'failed'::character varying::text, 'cancelled'::character varying::text])),
  workflow_state jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  error_message text,
  completed_at timestamp with time zone,
  started_at timestamp with time zone,
  deleted_at timestamp with time zone,
  elevenlabs_job_id character varying,
  source_language character varying DEFAULT 'auto'::character varying,
  estimated_cost numeric DEFAULT 0,
  actual_cost numeric,
  cost_breakdown jsonb DEFAULT '{}'::jsonb,
  current_stage character varying,
  dubbing_metadata jsonb DEFAULT '{}'::jsonb,
  processing_time_seconds integer,
  CONSTRAINT processing_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_jobs_project FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  name text NOT NULL,
  description text,
  settings jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT projects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  channel_id text NOT NULL,
  callback_url text NOT NULL,
  topic text NOT NULL,
  lease_seconds integer NOT NULL,
  expires_at timestamp with time zone,
  secret text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'failed'::text])),
  last_verified_at timestamp with time zone,
  renewal_attempts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transcripts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL UNIQUE,
  video_id character varying NOT NULL,
  user_id text NOT NULL,
  language_code character varying NOT NULL CHECK (language_code::text ~* '^[a-z]{2}$'::text),
  transcript_text text NOT NULL,
  word_timestamps jsonb DEFAULT '[]'::jsonb,
  provider character varying DEFAULT 'elevenlabs'::character varying,
  confidence_score numeric,
  duration integer,
  status character varying DEFAULT 'completed'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transcripts_pkey PRIMARY KEY (id),
  CONSTRAINT transcripts_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id)
);
CREATE TABLE public.translations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transcript_id uuid,
  job_id uuid NOT NULL,
  video_id character varying NOT NULL,
  user_id text NOT NULL,
  source_language character varying NOT NULL CHECK (source_language::text ~* '^[a-z]{2}$'::text),
  target_language character varying NOT NULL CHECK (target_language::text ~* '^[a-z]{2}$'::text),
  translated_text text NOT NULL,
  word_timestamps jsonb DEFAULT '[]'::jsonb,
  provider character varying DEFAULT 'elevenlabs'::character varying,
  confidence_score numeric,
  status character varying DEFAULT 'completed'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  reviewed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT translations_pkey PRIMARY KEY (id),
  CONSTRAINT translations_transcript_id_fkey FOREIGN KEY (transcript_id) REFERENCES public.transcripts(id),
  CONSTRAINT translations_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  name text,
  avatar_url text,
  access_token text,
  refresh_token text,
  token_expiry timestamp with time zone,
  preferences jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.videos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  video_id character varying NOT NULL UNIQUE,
  user_id text NOT NULL,
  project_id uuid,
  channel_id character varying,
  channel_name text,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  storage_url text,
  video_url text,
  duration integer,
  view_count bigint DEFAULT 0,
  like_count bigint DEFAULT 0,
  comment_count bigint DEFAULT 0,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'queued'::character varying, 'processing'::character varying, 'live'::character varying, 'failed'::character varying, 'not-started'::character varying]::text[])),
  language_code character varying CHECK (language_code IS NULL OR language_code::text ~* '^[a-z]{2}$'::text),
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  video_type character varying CHECK (video_type IS NULL OR (video_type::text = ANY (ARRAY['original'::character varying, 'translated'::character varying]::text[]))),
  source_video_id character varying,
  deleted_at timestamp with time zone,
  CONSTRAINT videos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_videos_project FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT fk_videos_source FOREIGN KEY (source_video_id) REFERENCES public.videos(video_id)
);
CREATE TABLE public.youtube_connections (
  connection_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  youtube_channel_id text NOT NULL,
  youtube_channel_name text,
  channel_avatar_url text,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  token_expiry timestamp with time zone,
  is_primary boolean NOT NULL DEFAULT false,
  language_code character varying,
  master_connection_id uuid,
  connection_type text NOT NULL DEFAULT 'satellite'::text CHECK (connection_type = ANY (ARRAY['master'::text, 'satellite'::text, 'reconnect'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT youtube_connections_pkey PRIMARY KEY (connection_id),
  CONSTRAINT youtube_connections_master_connection_id_fkey FOREIGN KEY (master_connection_id) REFERENCES public.youtube_connections(connection_id)
);